import turtle
turtle.Screen().colormode(255)
turtle_t = turtle.Turtle()
turtle_t.shape("turtle")
for i in range(10):
    turtle_t.forward(100)
    turtle_t.right(180)
    turtle_t.forward(10)
    turtle_t.right(120)
    turtle_t.forward(10)
    turtle_t.right(180)
    turtle_t.forward(10)
    turtle_t.right(300)
    turtle_t.forward(10)
    turtle_t.right(180)
    turtle_t.forward(10)
    turtle_t.right(300)
    turtle_t.forward(90)
    turtle_t.right(45)
turtle.done()